### PR TITLE
Check manifest `mediaType` field on validation

### LINKED ISSUE #446: NPE on missing mediaType in manifest.json
If manifest JSON doesn't have `mediaType` field, the adapter fails with `NullPointerException`. Instead of this, the adapter should return `MANIFEST_INVALID` error, see https://docs.docker.com/registry/spec/api/

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #446 
`mediaType` field in manifest json is required. I've added corresponding check in validation process on upload, corrected `JsonManifest` to throw `InvalidManifestException` when required fields are absent, fixed tests where necessary.

### CODE REVIEW

File: src/main/java/com/artipie/docker/asto/AstoManifests.java [hunk 1]
```diff
@@ -157,17 +157,30 @@ public AstoManifests(
...
                         }
-                        return CompletableFuture.allOf();
-                    }
-                ).toCompletableFuture()
+                    ).toCompletableFuture()
+                ),
+                Stream.of(
+                    CompletableFuture.runAsync(
+                        () -> {
+                            if (manifest.mediaType().isEmpty()) {
```
Comment (genryxy) [inline src/main/java/com/artipie/docker/asto/AstoManifests.java:176]: @olenagerasimova let's use `isPresent()` here as our colleagues use Java 8

**Review by genryxy — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, one comment

File: src/main/java/com/artipie/docker/asto/AstoManifests.java (hunk 1 above)
Comment (olenagerasimova) [reply src/main/java/com/artipie/docker/asto/AstoManifests.java:176]: @genryxy it's not an optional, simple string

Comment (genryxy) [reply src/main/java/com/artipie/docker/asto/AstoManifests.java:176]: @olenagerasimova got it, sorry

**Review by genryxy — APPROVED** [review]
@olenagerasimova looks good to me
